name: Warp
author: Gero
version: 0.0.1
main: de.lowkeys.warp.main.WarpMain
depend: [Core]
commands:
   warp:
      name: warp
   createwarp:
      name: createwarp
   delwarp:
      name: delwarp
   editwarp:
      name: editwarp